//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace KnockoutStudy.Model
{
    public partial class KnockOutEntities : ObjectContext
    {
        public const string ConnectionString = "name=KnockOutEntities";
        public const string ContainerName = "KnockOutEntities";
    
        #region Constructors
    
        public KnockOutEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public KnockOutEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public KnockOutEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Friend> Friend
        {
            get { return _friend  ?? (_friend = CreateObjectSet<Friend>("Friend")); }
        }
        private ObjectSet<Friend> _friend;

        #endregion
    }
}
